/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bab_3;

import Bab_3.RentalMotorBulanan;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mhmd Aminuddin
 */
public class Rental_MotorGUI extends javax.swing.JFrame {

    private JTextField tfMerk = new JTextField();


    /**
     * Creates new form Rental_MotorGUI
     */
    public Rental_MotorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        txtPlat = new javax.swing.JTextField();
        txtDurasi = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnHarian = new javax.swing.JButton();
        btnBulanan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memo1 = new javax.swing.JTextArea();
        txtMerk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Rental Motor");

        jLabel2.setText("Nama Pelanggan:");

        jLabel3.setText("Merk Motor:");

        jLabel4.setText("Plat Nomor:");

        jLabel5.setText("Durasi (Hari/Bulan):");

        jLabel6.setText("Harga per Hari/Bulan:");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        txtPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlatActionPerformed(evt);
            }
        });

        txtDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiActionPerformed(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        btnHarian.setText("Harian");
        btnHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarianActionPerformed(evt);
            }
        });

        btnBulanan.setText("Bulanan");
        btnBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBulananActionPerformed(evt);
            }
        });

        memo1.setColumns(20);
        memo1.setRows(5);
        jScrollPane1.setViewportView(memo1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(btnBulanan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnHarian)
                                    .addComponent(tfNama)
                                    .addComponent(txtPlat)
                                    .addComponent(txtDurasi)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBulanan)
                    .addComponent(btnHarian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void btnHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarianActionPerformed
        // TODO add your handling code here:
    try {
    // Cek apakah tfMerk sudah tidak null
    if (tfNama == null || txtMerk == null || txtPlat == null || txtDurasi == null || txtHarga == null) {
        memo1.setText("Komponen input tidak valid.");
        return;
    }
    // Ambil teks dari JTextField dan cek apakah kosong
    String nama = tfNama.getText().trim();
    String merk = txtMerk.getText().trim();
    String plat = txtPlat.getText().trim();
    String durasiStr = txtDurasi.getText().trim();
    String hargaStr = txtHarga.getText().trim();
    // Cek apakah ada input yang kosong
    if (nama.isEmpty() || merk.isEmpty() || plat.isEmpty() || durasiStr.isEmpty() || hargaStr.isEmpty()) {
        memo1.setText("Semua field harus diisi!");
        return;
    }
    // Validasi durasi dan harga agar berupa angka
    int durasi = 0;
    int harga = 0;
    try {
        durasi = Integer.parseInt(durasiStr);
        harga = Integer.parseInt(hargaStr);
    } catch (NumberFormatException ex) {
        memo1.setText("Durasi dan harga harus berupa angka!");
        return;
    }
    // Cek apakah durasi dan harga valid (positif)
    if (durasi <= 0 || harga <= 0) {
        memo1.setText("Durasi dan harga harus lebih besar dari 0.");
        return;
    }
    // Buat objek RentalMotorBulanan
    RentalMotorBulanan motor = new RentalMotorBulanan(nama, merk, plat, durasi, harga);
    int total = motor.hitungTotal();
    // Tampilkan output
    String output = 
        "Nama: " + nama + "\n" +
        "Merk: " + merk + "\n" +
        "Plat: " + plat + "\n" +
        "Durasi: " + durasi + " bulan\n" +
        "Total Sewa: Rp" + total;

    memo1.setText(output); // tampilkan di JTextArea
} catch (Exception ex) {
    memo1.setText("Terjadi kesalahan saat memproses input.");
    ex.printStackTrace();
}
    }//GEN-LAST:event_btnHarianActionPerformed

    private void txtPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatActionPerformed

    private void btnBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBulananActionPerformed
        // TODO add your handling code here:
    try {
        String nama = tfNama.getText().trim();
        String merk = txtMerk.getText().trim();
        String plat = txtPlat.getText().trim();
        String durasiStr = txtDurasi.getText().trim();
        String hargaStr = txtHarga.getText().trim();

        if (nama.isEmpty() || merk.isEmpty() || plat.isEmpty() || durasiStr.isEmpty() || hargaStr.isEmpty()) {
            memo1.setText("Semua field harus diisi!");
            return;
        }

        int durasi = Integer.parseInt(durasiStr);
        int harga = Integer.parseInt(hargaStr);

        RentalMotorBulanan motor = new RentalMotorBulanan(nama, merk, plat, durasi, harga);
        int total = motor.hitungTotal();

        String output =
            "Nama: " + nama + "\n" +
            "Merk: " + merk + "\n" +
            "Plat: " + plat + "\n" +
            "Durasi: " + durasi + " bulan\n" +
            "Total Sewa: Rp" + total;

        memo1.setText(output);
    } catch (NumberFormatException ex) {
        memo1.setText("Durasi dan harga harus berupa angka!");
        ex.printStackTrace();
    } catch (Exception ex) {
        memo1.setText("Terjadi kesalahan saat memproses input.");
        ex.printStackTrace();
    }

    }//GEN-LAST:event_btnBulananActionPerformed

    private void txtDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rental_MotorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rental_MotorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rental_MotorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rental_MotorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rental_MotorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBulanan;
    private javax.swing.JButton btnHarian;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memo1;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtPlat;
    // End of variables declaration//GEN-END:variables
}
